name=LCP_sett
version=1.0.0
author=jim lee
maintainer=sett@leftcoast.biz
sentence=A version of the Sett game (Pattern matching). Runs under lilOS.
paragraph=It's a card game for matching shaped, colors etc. Runs on an Arduino running under lilOS.
category=Other
url=https://github.com/leftCoast/LCP_sett
architectures=*
depends=LC_lilOS
dot_a_linkage=true
